### ISSUE TITLE
Message error NOd Red "Error: School Holiday API is returning no records"

### ISSUE THREAD

**Issue by Apollon16** [tataille/node-red-french-holidays#5]
hello, For a few days I have this error from Node red "Error: School Holiday API is returning no records".
What should we do in this case? THANKS

![Capture d’écran 2023-04-03 175545](https://user-images.githubusercontent.com/89293183/229563542-8facb0cd-354e-4b9e-bba6-00f3a827dd08.png)

![Capture d’écran 2023-04-03 205328](https://user-images.githubusercontent.com/89293183/229600832-4edb1b49-6f85-4543-b2fe-f5675dd3ce3a.png)

**Comment by tataille** [comment]
Hi, this error is just a warning message (I could change the type of message). Sometime the official API is returning null value, and in the previous version it causes the nodered server to stop running.

Solution is in this case to ask again for value (poll)

**Comment by tataille** [comment]
Due to the fact the plugin interact with external APIs provided by French government, external errors (missing records, connection errors..) are thrown to the node-red core. To handle the exceptions and program a new query, a catch block must be added to the node-red flow. Error details can be found in the exception message payload.

**Comment by tataille** [comment]
The README.md describe the error handling:
_"Due to the fact the plugin interact with external APIs provided by French government, external errors (missing records, connection errors..) are thrown to the node-red core. To handle the exceptions and program a new query, a catch block must be added to the node-red flow. Error details can be found in the exception message payload."_
